### ISSUE TITLE
 stack-installer/ubuntu-20.04.sh procudes talib that causes problems 

### ISSUE THREAD

**Issue by poe28** [jesse-ai/stack-installer#10]
On a fresh Hetzner Ubuntu 20.04, I have run `stack-installer/ubuntu-20.04.sh`.
After that, I cannot import talib (and neither can jesse import it):
```
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import talib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/till/.local/lib/python3.8/site-packages/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
But a `pip3 uninstall TA-lib; pip3 install TA-lib` solves the problem, and you get `_ta_lib.cpython-38-x86_64-linux-gnu.so`as well. So it seems that there is no need to compile it from sources.

**Comment by saleh-mir** [comment]
This is probably some issue with the version of those packages at that point in time. I'm guessing they are solved now. Also I added a new script for Ubuntu 22.04. Sorry I missed this.
